"""food table

Revision ID: 0efcac560783
Revises: 0f2279d9284c
Create Date: 2018-03-10 22:46:03.605539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0efcac560783'
down_revision = '0f2279d9284c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.String(length=140), nullable=True),
    sa.Column('kcal', sa.Numeric(), nullable=True),
    sa.Column('protein', sa.Numeric(), nullable=True),
    sa.Column('fat', sa.Numeric(), nullable=True),
    sa.Column('carbs', sa.Numeric(), nullable=True),
    sa.Column('meal', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food')
    # ### end Alembic commands ###
