"""foods table

Revision ID: 3ac5175413c3
Revises: 9472eacc96b8
Create Date: 2018-03-14 23:13:37.012394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ac5175413c3'
down_revision = '9472eacc96b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('count', sa.Numeric(precision=10, scale=0), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food', 'count')
    # ### end Alembic commands ###
