"""empty message

Revision ID: 3f020ef3c85d
Revises: ba6632e2cf84
Create Date: 2018-03-16 13:46:38.837168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f020ef3c85d'
down_revision = 'ba6632e2cf84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_food_date'), 'food', ['date'], unique=False)
    op.add_column('user', sa.Column('calories_goal', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('carb_goal', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('fat_goal', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('protein_goal', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'protein_goal')
    op.drop_column('user', 'fat_goal')
    op.drop_column('user', 'carb_goal')
    op.drop_column('user', 'calories_goal')
    op.drop_index(op.f('ix_food_date'), table_name='food')
    # ### end Alembic commands ###
