"""foods table

Revision ID: 7cb807b7a74a
Revises: 0efcac560783
Create Date: 2018-03-14 12:44:19.256942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cb807b7a74a'
down_revision = '0efcac560783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('ndbno', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food', 'ndbno')
    # ### end Alembic commands ###
