"""foods table

Revision ID: 9472eacc96b8
Revises: 7cb807b7a74a
Create Date: 2018-03-14 23:02:12.668360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9472eacc96b8'
down_revision = '7cb807b7a74a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('unit', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food', 'unit')
    # ### end Alembic commands ###
