"""empty message

Revision ID: a2dd9dd3b0e0
Revises: 3f020ef3c85d
Create Date: 2018-03-16 15:40:07.726863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2dd9dd3b0e0'
down_revision = '3f020ef3c85d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('carbs_grams', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('fat_grams', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('protein_grams', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'protein_grams')
    op.drop_column('user', 'fat_grams')
    op.drop_column('user', 'carbs_grams')
    # ### end Alembic commands ###
