"""foods table date

Revision ID: ba6632e2cf84
Revises: 3ac5175413c3
Create Date: 2018-03-15 21:43:22.287952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba6632e2cf84'
down_revision = '3ac5175413c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food', 'date')
    # ### end Alembic commands ###
